"""bind work items to workflows

Revision ID: 07e6c51faaf8
Revises: 52d7b299b349
Create Date: 2026-08-27 15:33:12.295416
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "07e6c51faaf8"
down_revision: str | None = "52d7b299b349"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items") as batch_op:
        batch_op.add_column(sa.Column("workflow_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("workflow_state_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_work_items_workflow_state_id", "workflow_states", ["workflow_state_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_work_items_workflow_id", "workflows", ["workflow_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items") as batch_op:
        batch_op.drop_constraint("fk_work_items_workflow_state_id", type_="foreignkey")
        batch_op.drop_constraint("fk_work_items_workflow_id", type_="foreignkey")
        batch_op.drop_column("workflow_state_id")
        batch_op.drop_column("workflow_id")
    # ### end Alembic commands ###
