"""omnichannel and integrations

Revision ID: 23f48126a257
Revises: 9f06d4e34f7a
Create Date: 2026-08-27 15:41:01.981396
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "23f48126a257"
down_revision: str | None = "9f06d4e34f7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("secret_ref", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(
        op.f("ix_integrations_organization_id"), "integrations", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_integrations_provider"), "integrations", ["provider"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", "channel"),
    )
    op.create_index(
        op.f("ix_notification_preferences_organization_id"),
        "notification_preferences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "external_entity_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("external_url", sa.String(length=1000), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id", "entity_type", "external_id"),
    )
    op.create_index(
        op.f("ix_external_entity_references_entity_id"),
        "external_entity_references",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_entity_references_integration_id"),
        "external_entity_references",
        ["integration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_entity_references_organization_id"),
        "external_entity_references",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "identity_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("external_user_id", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id", "external_user_id"),
    )
    op.create_index(
        op.f("ix_identity_links_integration_id"), "identity_links", ["integration_id"], unique=False
    )
    op.create_index(
        op.f("ix_identity_links_organization_id"),
        "identity_links",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_identity_links_user_id"), "identity_links", ["user_id"], unique=False)
    op.create_table(
        "outbound_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_outbound_messages_channel"), "outbound_messages", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_messages_organization_id"),
        "outbound_messages",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_messages_status"), "outbound_messages", ["status"], unique=False
    )
    op.create_table(
        "webhook_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id", "external_event_id"),
    )
    op.create_index(
        op.f("ix_webhook_receipts_integration_id"),
        "webhook_receipts",
        ["integration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_receipts_organization_id"),
        "webhook_receipts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_receipts_status"), "webhook_receipts", ["status"], unique=False
    )
    op.create_table(
        "inbound_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("external_user_id", sa.String(length=200), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inbound_messages_channel"), "inbound_messages", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_inbound_messages_external_user_id"),
        "inbound_messages",
        ["external_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_messages_integration_id"),
        "inbound_messages",
        ["integration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_messages_organization_id"),
        "inbound_messages",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_messages_status"), "inbound_messages", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbound_messages_status"), table_name="inbound_messages")
    op.drop_index(op.f("ix_inbound_messages_organization_id"), table_name="inbound_messages")
    op.drop_index(op.f("ix_inbound_messages_integration_id"), table_name="inbound_messages")
    op.drop_index(op.f("ix_inbound_messages_external_user_id"), table_name="inbound_messages")
    op.drop_index(op.f("ix_inbound_messages_channel"), table_name="inbound_messages")
    op.drop_table("inbound_messages")
    op.drop_index(op.f("ix_webhook_receipts_status"), table_name="webhook_receipts")
    op.drop_index(op.f("ix_webhook_receipts_organization_id"), table_name="webhook_receipts")
    op.drop_index(op.f("ix_webhook_receipts_integration_id"), table_name="webhook_receipts")
    op.drop_table("webhook_receipts")
    op.drop_index(op.f("ix_outbound_messages_status"), table_name="outbound_messages")
    op.drop_index(op.f("ix_outbound_messages_organization_id"), table_name="outbound_messages")
    op.drop_index(op.f("ix_outbound_messages_channel"), table_name="outbound_messages")
    op.drop_table("outbound_messages")
    op.drop_index(op.f("ix_identity_links_user_id"), table_name="identity_links")
    op.drop_index(op.f("ix_identity_links_organization_id"), table_name="identity_links")
    op.drop_index(op.f("ix_identity_links_integration_id"), table_name="identity_links")
    op.drop_table("identity_links")
    op.drop_index(
        op.f("ix_external_entity_references_organization_id"),
        table_name="external_entity_references",
    )
    op.drop_index(
        op.f("ix_external_entity_references_integration_id"),
        table_name="external_entity_references",
    )
    op.drop_index(
        op.f("ix_external_entity_references_entity_id"), table_name="external_entity_references"
    )
    op.drop_table("external_entity_references")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_index(
        op.f("ix_notification_preferences_organization_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_integrations_provider"), table_name="integrations")
    op.drop_index(op.f("ix_integrations_organization_id"), table_name="integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
