"""workflows approvals deliverables sla automation

Revision ID: 52d7b299b349
Revises: 9fedf4989dc7
Create Date: 2026-08-27 15:31:10.279883
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "52d7b299b349"
down_revision: str | None = "9fedf4989dc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("trigger_event", sa.String(length=100), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_automations_organization_id"), "automations", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_automations_trigger_event"), "automations", ["trigger_event"], unique=False
    )
    op.create_table(
        "slas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("response_minutes", sa.Integer(), nullable=False),
        sa.Column("resolution_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(op.f("ix_slas_organization_id"), "slas", ["organization_id"], unique=False)
    op.create_table(
        "workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", "version"),
    )
    op.create_index(
        op.f("ix_workflows_organization_id"), "workflows", ["organization_id"], unique=False
    )
    op.create_table(
        "automation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("automation_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["automation_id"],
            ["automations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_automation_runs_automation_id"), "automation_runs", ["automation_id"], unique=False
    )
    op.create_index(
        op.f("ix_automation_runs_organization_id"),
        "automation_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "workflow_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("initial", sa.Boolean(), nullable=False),
        sa.Column("terminal", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "code"),
    )
    op.create_index(
        op.f("ix_workflow_states_workflow_id"), "workflow_states", ["workflow_id"], unique=False
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("requested_from", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("amount", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("decision_by", sa.Uuid(), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_requests_organization_id"),
        "approval_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_requested_from"),
        "approval_requests",
        ["requested_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_status"), "approval_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_work_item_id"),
        "approval_requests",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("from_state_id", sa.Uuid(), nullable=False),
        sa.Column("to_state_id", sa.Uuid(), nullable=False),
        sa.Column("required_permission", sa.String(length=100), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_state_id"],
            ["workflow_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_state_id"],
            ["workflow_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "from_state_id", "to_state_id"),
    )
    op.create_index(
        op.f("ix_workflow_transitions_workflow_id"),
        "workflow_transitions",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "deliverables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attachment_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliverables_organization_id"), "deliverables", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_deliverables_status"), "deliverables", ["status"], unique=False)
    op.create_index(
        op.f("ix_deliverables_work_item_id"), "deliverables", ["work_item_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliverables_work_item_id"), table_name="deliverables")
    op.drop_index(op.f("ix_deliverables_status"), table_name="deliverables")
    op.drop_index(op.f("ix_deliverables_organization_id"), table_name="deliverables")
    op.drop_table("deliverables")
    op.drop_index(op.f("ix_workflow_transitions_workflow_id"), table_name="workflow_transitions")
    op.drop_table("workflow_transitions")
    op.drop_index(op.f("ix_approval_requests_work_item_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_status"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_requested_from"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_organization_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_workflow_states_workflow_id"), table_name="workflow_states")
    op.drop_table("workflow_states")
    op.drop_index(op.f("ix_automation_runs_organization_id"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_automation_id"), table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index(op.f("ix_workflows_organization_id"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_slas_organization_id"), table_name="slas")
    op.drop_table("slas")
    op.drop_index(op.f("ix_automations_trigger_event"), table_name="automations")
    op.drop_index(op.f("ix_automations_organization_id"), table_name="automations")
    op.drop_table("automations")
    # ### end Alembic commands ###
