"""sla execution and idempotent automation

Revision ID: 9f06d4e34f7a
Revises: 07e6c51faaf8
Create Date: 2026-08-27 15:36:51.886509
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9f06d4e34f7a"
down_revision: str | None = "07e6c51faaf8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("automation_runs", sa.Column("event_key", sa.String(length=160), nullable=True))
    runs = sa.table(
        "automation_runs",
        sa.column("id", sa.Uuid()),
        sa.column("event_key", sa.String()),
    )
    connection = op.get_bind()
    for run_id in connection.execute(sa.select(runs.c.id)).scalars():
        connection.execute(
            runs.update().where(runs.c.id == run_id).values(event_key=f"legacy:{run_id}")
        )
    with op.batch_alter_table("automation_runs") as batch_op:
        batch_op.alter_column("event_key", existing_type=sa.String(length=160), nullable=False)
        batch_op.create_unique_constraint(
            "uq_automation_runs_automation_event", ["automation_id", "event_key"]
        )
    with op.batch_alter_table("work_items") as batch_op:
        batch_op.add_column(sa.Column("sla_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("response_due_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("resolution_due_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("sla_escalated_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_foreign_key("fk_work_items_sla_id", "slas", ["sla_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items") as batch_op:
        batch_op.drop_constraint("fk_work_items_sla_id", type_="foreignkey")
        batch_op.drop_column("sla_escalated_at")
        batch_op.drop_column("responded_at")
        batch_op.drop_column("resolution_due_at")
        batch_op.drop_column("response_due_at")
        batch_op.drop_column("sla_id")
    with op.batch_alter_table("automation_runs") as batch_op:
        batch_op.drop_constraint("uq_automation_runs_automation_event", type_="unique")
        batch_op.drop_column("event_key")
    # ### end Alembic commands ###
