"""phase two files relations and views

Revision ID: 9fedf4989dc7
Revises: 5d0511d150eb
Create Date: 2026-08-27 15:27:45.298252
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9fedf4989dc7"
down_revision: str | None = "5d0511d150eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_attachments_organization_id"), "attachments", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_work_item_id"), "attachments", ["work_item_id"], unique=False
    )
    op.create_table(
        "work_item_relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["work_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "source_id", "target_id", "relation_type"),
    )
    op.create_index(
        op.f("ix_work_item_relations_organization_id"),
        "work_item_relations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_relations_source_id"), "work_item_relations", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_item_relations_target_id"), "work_item_relations", ["target_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_item_relations_target_id"), table_name="work_item_relations")
    op.drop_index(op.f("ix_work_item_relations_source_id"), table_name="work_item_relations")
    op.drop_index(op.f("ix_work_item_relations_organization_id"), table_name="work_item_relations")
    op.drop_table("work_item_relations")
    op.drop_index(op.f("ix_attachments_work_item_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_organization_id"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###
