"""conciencia agents and process intelligence

Revision ID: ab026585cbe0
Revises: 23f48126a257
Create Date: 2026-08-27 15:46:20.994029
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ab026585cbe0"
down_revision: str | None = "23f48126a257"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(op.f("ix_agents_organization_id"), "agents", ["organization_id"], unique=False)
    op.create_table(
        "process_recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("recommendation", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_process_recommendations_kind"), "process_recommendations", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_process_recommendations_organization_id"),
        "process_recommendations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "agent_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "code"),
    )
    op.create_index(
        op.f("ix_agent_capabilities_agent_id"), "agent_capabilities", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_capabilities_code"), "agent_capabilities", ["code"], unique=False
    )
    op.create_table(
        "agent_permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "permission_code"),
    )
    op.create_index(
        op.f("ix_agent_permissions_agent_id"), "agent_permissions", ["agent_id"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("capability", sa.String(length=100), nullable=False),
        sa.Column("input_summary", sa.String(length=500), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_agent_id"), "agent_runs", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_organization_id"), "agent_runs", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_requested_by"), "agent_runs", ["requested_by"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_table(
        "agent_action_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_by", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_action_proposals_agent_run_id"),
        "agent_action_proposals",
        ["agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_action_proposals_organization_id"),
        "agent_action_proposals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_action_proposals_status"), "agent_action_proposals", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agent_action_proposals_target_id"),
        "agent_action_proposals",
        ["target_id"],
        unique=False,
    )
    op.create_table(
        "agent_approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["agent_action_proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proposal_id"),
    )
    op.create_index(
        op.f("ix_agent_approvals_organization_id"),
        "agent_approvals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_approvals_proposal_id"), "agent_approvals", ["proposal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_approvals_proposal_id"), table_name="agent_approvals")
    op.drop_index(op.f("ix_agent_approvals_organization_id"), table_name="agent_approvals")
    op.drop_table("agent_approvals")
    op.drop_index(op.f("ix_agent_action_proposals_target_id"), table_name="agent_action_proposals")
    op.drop_index(op.f("ix_agent_action_proposals_status"), table_name="agent_action_proposals")
    op.drop_index(
        op.f("ix_agent_action_proposals_organization_id"), table_name="agent_action_proposals"
    )
    op.drop_index(
        op.f("ix_agent_action_proposals_agent_run_id"), table_name="agent_action_proposals"
    )
    op.drop_table("agent_action_proposals")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_requested_by"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_organization_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_agent_permissions_agent_id"), table_name="agent_permissions")
    op.drop_table("agent_permissions")
    op.drop_index(op.f("ix_agent_capabilities_code"), table_name="agent_capabilities")
    op.drop_index(op.f("ix_agent_capabilities_agent_id"), table_name="agent_capabilities")
    op.drop_table("agent_capabilities")
    op.drop_index(
        op.f("ix_process_recommendations_organization_id"), table_name="process_recommendations"
    )
    op.drop_index(op.f("ix_process_recommendations_kind"), table_name="process_recommendations")
    op.drop_table("process_recommendations")
    op.drop_index(op.f("ix_agents_organization_id"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
