"""configurable work model and outbox

Revision ID: fbb8a7715582
Revises: 87a09f598a10
Create Date: 2026-08-27 16:14:41.833489
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fbb8a7715582"
down_revision: str | None = "87a09f598a10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_field_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "key"),
    )
    op.create_index(
        op.f("ix_custom_field_definitions_organization_id"),
        "custom_field_definitions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"), "outbox_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_next_attempt_at"), "outbox_events", ["next_attempt_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_organization_id"), "outbox_events", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(op.f("ix_tags_organization_id"), "tags", ["organization_id"], unique=False)
    op.create_table(
        "work_item_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("form_schema", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code"),
    )
    op.create_index(
        op.f("ix_work_item_types_organization_id"),
        "work_item_types",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "business_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(
        op.f("ix_business_units_organization_id"),
        "business_units",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "custom_field_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("definition_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["custom_field_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_item_id", "definition_id"),
    )
    op.create_index(
        op.f("ix_custom_field_values_definition_id"),
        "custom_field_values",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_field_values_organization_id"),
        "custom_field_values",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_field_values_work_item_id"),
        "custom_field_values",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "expected_deliverables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expected_deliverables_organization_id"),
        "expected_deliverables",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expected_deliverables_work_item_id"),
        "expected_deliverables",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "work_item_tags",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_item_id"], ["work_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("work_item_id", "tag_id"),
    )
    with op.batch_alter_table("departments") as batch_op:
        batch_op.add_column(sa.Column("business_unit_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_departments_business_unit_id", "business_units", ["business_unit_id"], ["id"]
        )
    with op.batch_alter_table("memberships") as batch_op:
        batch_op.add_column(sa.Column("supervisor_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("phone", sa.String(length=40), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("whatsapp_id", sa.String(length=120), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("telegram_id", sa.String(length=120), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "timezone", sa.String(length=60), nullable=False, server_default="America/Asuncion"
            )
        )
        batch_op.add_column(
            sa.Column("work_schedule", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )
        batch_op.add_column(
            sa.Column("location", sa.String(length=160), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("responsibilities", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(
            sa.Column("specialties", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
    with op.batch_alter_table("work_items") as batch_op:
        batch_op.add_column(sa.Column("type_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("impact", sa.String(length=30), nullable=False, server_default="INDIVIDUAL")
        )
        batch_op.add_column(
            sa.Column("urgency", sa.String(length=20), nullable=False, server_default="NORMAL")
        )
        batch_op.add_column(
            sa.Column("category", sa.String(length=120), nullable=False, server_default="")
        )
        batch_op.add_column(sa.Column("source_department_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("destination_department_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("branch", sa.String(length=160), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "expected_deliverable", sa.String(length=500), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column("custom_data", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )
        batch_op.add_column(
            sa.Column("metadata_json", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )
        batch_op.create_foreign_key("fk_work_items_type_id", "work_item_types", ["type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_items") as batch_op:
        batch_op.drop_constraint("fk_work_items_type_id", type_="foreignkey")
        for column in (
            "metadata_json",
            "custom_data",
            "expected_deliverable",
            "branch",
            "destination_department_id",
            "source_department_id",
            "category",
            "urgency",
            "impact",
            "type_id",
        ):
            batch_op.drop_column(column)
    with op.batch_alter_table("memberships") as batch_op:
        for column in (
            "specialties",
            "responsibilities",
            "location",
            "work_schedule",
            "timezone",
            "telegram_id",
            "whatsapp_id",
            "phone",
            "supervisor_id",
        ):
            batch_op.drop_column(column)
    with op.batch_alter_table("departments") as batch_op:
        batch_op.drop_constraint("fk_departments_business_unit_id", type_="foreignkey")
        batch_op.drop_column("business_unit_id")
    op.drop_table("work_item_tags")
    op.drop_index(op.f("ix_expected_deliverables_work_item_id"), table_name="expected_deliverables")
    op.drop_index(
        op.f("ix_expected_deliverables_organization_id"), table_name="expected_deliverables"
    )
    op.drop_table("expected_deliverables")
    op.drop_index(op.f("ix_custom_field_values_work_item_id"), table_name="custom_field_values")
    op.drop_index(op.f("ix_custom_field_values_organization_id"), table_name="custom_field_values")
    op.drop_index(op.f("ix_custom_field_values_definition_id"), table_name="custom_field_values")
    op.drop_table("custom_field_values")
    op.drop_index(op.f("ix_business_units_organization_id"), table_name="business_units")
    op.drop_table("business_units")
    op.drop_index(op.f("ix_work_item_types_organization_id"), table_name="work_item_types")
    op.drop_table("work_item_types")
    op.drop_index(op.f("ix_tags_organization_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_outbox_events_status"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_organization_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_next_attempt_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(
        op.f("ix_custom_field_definitions_organization_id"), table_name="custom_field_definitions"
    )
    op.drop_table("custom_field_definitions")
    # ### end Alembic commands ###
